### ISSUE TITLE
Variable not dereferenced with include tasks

### ISSUE THREAD

**Issue by rajeshjadhav** [apigee/henchman#104]
```
  - name: Include Standard playbook
    include: "foo-bar/foo-standard.yaml"
    vars:
      component: {{ zookeeper_profile }}
      version: {{ zookeeper_version }}
```
