### ISSUE TITLE
Throw Error for duplicate keys in YAML file

### ISSUE THREAD

**Issue by jlin21** [apigee/henchman#15]
Currently the YAML unmarshaller (including the custom ones) cannot handle multiple include cases:

``` yaml
name: "Sample plan"
vars:
  hello: world
  foo: scar
  include:
    - test/vars/vars.yaml
  include:
    - test/vars/vars2.yaml
  spam: eggs
tasks:
  - name: Sample task that does nothing
    action: cmd="ls"
  - name: Second task
    action: cmd="echo"
    ignore_errors: true

This won't throw a "multiple includes error" it will just take any value from any include field (depends on which value was added last) as long as the include value follows the right format.
```

**Comment by jlin21** [comment]
This applies for anything duplicate keys.  YAML will silently ignore any duplicate keys.

``` yaml
name: "bad tasks"
tasks:
  - include: tmp/task
    include: tmp/task1
    shell:  cmd=hello
    shell: cmd=no
```

Will not throw any errors because the initial YAML unmarshaller turns everything into a `map[interface{}]interface{}` so include and shell will just be overwritten by any subsequent value.
