### ISSUE TITLE
Need a way to override sudo execution.

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#52]
Currently, "sudo: true" is at the root level, which means all the build steps will get executed as sudo. If we need to execute a particular step in between as non-sudo, we don't have option for that.

``` yaml
name: "Install Management Server"
sudo: true
vars:
  openjdk: "java-1.7.0-openjdk"
  edge_install_dir: "/opt"
  profile: "edge-management-server"

hosts:
  - mgmt

tasks:
  - name: Stop iptables
    shell: cmd="service iptables stop"

  - name: Zip
    shell: chdir="files" cmd="zip -r token.zip token"
    local: true
    sudo: false #Expecting something like this

  - name: Copy token folder to /opt
    copy: src=files/token.zip dest=/opt/token.zip
```
