### ISSUE TITLE
Inventory should be available as part of variable map.

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#53]
All the data in the inventory should be available as part of vars map for accessing across the playbooks.

```
groups:
  zk:
    hosts:
      - 10.10.10.11
    vars:
      henchman_username: "build"

 mgmt
    hosts:
      - 10.10.10.12
    vars:
      henchman_username: "build"
```

I should be able to access `vars.zk.hosts` in the playbook.
