### ISSUE TITLE
Support for global variables across the groups, to be used in all playbooks

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#55]
Actual:

```
groups:
  zk:
    hosts:
      - 10.10.10.1
    vars:
      henchman_username: "build"
      henchman_keyfile: "/home/user/.ssh/id_rsa1.pem"
      install_dir: "/opt/apigee"
  cassandra:
    hosts:
      - 10.10.10.2
    vars:
      henchman_username: "build"
      henchman_keyfile: "/home/user/.ssh/id_rsa1.pem"
      install_dir: "/opt/apigee"
      schema_dir: /opt/schema"
 pg:
    hosts:
      - 10.10.10.3
    vars:
      henchman_username: "build"
      henchman_keyfile: "/home/user/.ssh/id_rsa2.pem"
      install_dir: "/opt/apigee"
      schema_dir: /opt/schema"
`
```

Expected:

```
groups:
  zk:
    hosts:
      - 10.10.10.1

  cassandra:
    hosts:
      - 10.10.10.2

  pg:
    hosts:
      - 10.10.10.3
    vars:
      henchman_keyfile: "/home/user/.ssh/id_rsa2.pem"

global_vars:
  henchman_username: "build"
  henchman_keyfile: "/home/user/.ssh/id_rsa1.pem"
  install_dir: "/opt/apigee"
  schema_dir: /opt/schema"
```

These global variables should be accessible something like `vars.global.install_dir`
This will simplify the inventory and the variables defined in each playbook.
