### ISSUE TITLE
When using "include" module, it expects the all the variable defined in library file to be present in the local playbook.

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#56]
**library/edge.yaml**

``` yaml
name: "Prepare Instances for Edge Installation"
sudo: true
vars:
  openjdk: "java-1.7.0-openjdk"
  edge_install_dir: "/opt/apigee"

hosts:
  - mgmt

tasks: 
  - name: Stop iptables
    shell: cmd="service iptables stop"  

  - name: Install openjdk
    yum: name="{{ vars.openjdk }}" state=present
```

**edge-management.yaml**

``` yaml
name: "Install Management Server"
sudo: true
vars:
  edge_install_dir: "/opt/apigee"
  profile: "edge-management-server"

hosts:
  - mgmt

tasks: 
  - include: "apigee-edge/edge-gateway.yaml"
```

Here the `openjdk` variable is not getting picked when it is defined in `library/edge.yaml`. It expects the variable to be defined in `edge-management.yaml`

**Comment by jlin21** [comment]
Calling an include in tasks expects the included task.yaml to be in the format of 

``` yaml
name: filler
tasks:
   -list
```
