### ISSUE TITLE
Need playbook level "ignore_errors: true"

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#63]
https://github.com/apigee/henchman/blob/master/henchman/test/plan/invalid/invalidIncludeFormatAtVarsLevel.yaml

Currently the `ignore_errors: true` is at the task level.
Need support at the plan level, just like `sudo: true`.

```
name: "Cleanup Edge Installations"
sudo: true
ignore_errors: true

hosts:
  - central_cassandra
  - zk
tasks: 
  - name: Stop Zookeeper if running
    shell: cmd="/opt/cassandra stop" loglevel=debug

  - name: Stop Zookeeper if running
    shell: cmd="/opt/zookeeper stop" loglevel=debug
```
