### ISSUE TITLE
Templating issue in When

### ISSUE THREAD

**Issue by jlin21** [apigee/henchman#67]
```
...
vars:
   service:
      - "hello"
      - "world"
tasks:
   name:  "Example Task"
   shell: cmd="hello" 
   when: hello|in:vars.service
```

Using filters with parameters in the when section will break the yaml parser because of the `:` syntax.  `:` is needed to pass params to filters.

A proposed solution would be to encase the key in `when`  with `''`.  E.G `when: 'hello|in:vars.service'` instead of `when: hello|in:vars.service`.
