### ISSUE TITLE
Henchman to work on local instance without the need of inventory.

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#84]
When I need to run set of command on local instance / the localhost itself, we still need inventory to be present. It will be great if we make the playbook to execute locally without the need of inventory.

**Comment by baskaran-md** [comment]
Example:

```
name: "Wiring the Cassandra & Provision Org. [Running Local]"
sudo: true
local: true
vars:
  include:
  - apigee-edge/apigee-vars.yaml

tasks:
  - name: Copy Registration File
    template: src="{{ vars.root_dir }}/files/edge-registration.sh" dest="{{ vars.edge_install_dir }}/edge-registration.sh"

  - name: Register Cassandra Servers  
    shell: cmd="sh {{ vars.edge_install_dir }}/edge-registration.sh" loglevel=debug
```
