### ISSUE TITLE
Variables should support internal reference. 

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#86]
```
name: "Global Variables"
vars:
  version: "1.7.0"

  zk_host: {{ vars.zookeeper | join:" " }}
  java_version: {{ vars.version }}
```

where `{{ vars.zookeeper }}` is the reference to inventory host
and, `{{ vars.version }}` is internal reference. 

```
groups:
  zookeeper:
    hosts:
      - 10.10.10.10
    vars:
      henchman_username: "ec2_user"
      henchman_keyfile: "~/.ssh/id_rsa"
```
