### ISSUE TITLE
Support "retry" for tasks.

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#87]
Need support for retrying each task separately. This will be helpful during installation failures due to flaky yum repos.

```
tasks: 
  - name: Install Cassandra RPM 
    yum: name="{{ vars.cassandra_profile }}" state=latest loglevel=debug
    retry: 3
```

This `retry` can be at the task level or at the playbook level. Task level overrides the playbook level.

```
name: "Install Cassandra"
sudo: true
retry: 3
vars:

hosts:
  - central_cassandra

tasks: 
  - name: Install Cassandra RPM 
    yum: name="{{ vars.cassandra_profile }}" state=latest loglevel=debug

  - name: Server Start
    shell: cmd="{{ vars.edge_install_dir }}/{{ vars.cassandra_profile }}/etc/init.d/{{ vars.cassandra_profile }} restart" loglevel=debug
    retry: 0
```

Here, the task "Install Cassandra RPM" will be retried 3 times, while "Server Start" will not be retried.
